map_names:
  - 阿努比斯神殿
  - 阿努比斯王座
  - 暴雪世界
  - 巴黎
  - 釜山
  - 多拉多
  - 艾兴瓦尔德
  - 埃斯佩兰萨
  - 绿洲城
  - 地平线月球基地
  - 月球基地
  - 哈瓦那
  - 花冈
  - 花村
  - 好莱坞
  - 伊利奥斯
  - 监测站：直布罗陀
  - 直布罗陀
  - 渣克镇
  - 国王大道
  - 南极半岛
  - 漓江塔
  - 尼泊尔
  - 努巴尼
  - 新皇后街
  - 新渣克城
  - 帕拉伊苏
  - 佩特拉
  - 斗兽场
  - 里阿尔托
  - 皇家赛道
  - 萨摩亚
  - 66号公路
  - 香巴里寺院
  - 苏拉瓦萨
  - 沃斯卡亚工业区
  - 中城
  - 阿瑜陀耶
