layout_version: 1280x800-v1

standard_size:
  width: 1280
  height: 800

rois:
  left_panel:
    x1: 35
    y1: 15
    x2: 220
    y2: 225

  run_code_panel:
    x1: 30
    y1: 185
    x2: 220
    y2: 225

  run_code_right_panel:
    x1: 1060
    y1: 80
    x2: 1240
    y2: 125

  achievement_panel:
    x1: 20
    y1: 225
    x2: 220
    y2: 315

  center_banner:
    x1: 300
    y1: 10
    x2: 1050
    y2: 100

  right_panel:
    x1: 1040
    y1: 0
    x2: 1275
    y2: 120

  bottom_left_hero:
    x1: 30
    y1: 620
    x2: 330
    y2: 790
